version: '3.8'

services:
  ollama:
    image: ollama/llama2:latest
    container_name: ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "11434:11434"
    volumes:
      - model-cache:/root/.ollama/models

  doc-chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc-chat-app
    depends_on:
      - ollama
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - cache_indices:/app/.cache_indices
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    device_requests:
      - driver: nvidia
        count: 0
        capabilities: ["gpu"]

volumes:
  cache_indices:
  model-cache:
